defaults:
  - _self_

session: traj_0
frames_dir: data/${session}/frames
frame_name: "000000.jpg"

# trained on ADE20K semantic segmentation
model:
  name: "oneformer"

cameras:
  - HAR1
  - HAR2
  - HAR3
  - HAR6
  - HAR8
  - new

output:
  dir: output/${session}/semantic